Repository agraboso/redux-api-middleware, pull requests merged in 2018-06, with the labels that each got.

#191 add docs on redux-thunk usage to readme
  README.md
Labels: docs

#193 Drop CALL_API alias
  README.md
  src/index.js
  test/index.js
Labels: Breaking Change

#194 Add custom `ok` hander (#171) + cleanup, docs, and tests
  README.md
  src/index.js
  src/middleware.js
  src/validation.js
  test/index.js
Labels: enhancement

#192 allow non-Symbol object properties on RSAA
  README.md
  src/validation.js
  test/index.js
Labels: Breaking Change
